# Generated by Django 4.2.6 on 2024-03-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_tiposervicio_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumos',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(null=True)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Facturado', models.BooleanField(default=False)),
                ('ID_Producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.producto')),
                ('ID_Reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.reserva')),
                ('ID_Servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.servicio')),
            ],
            options={
                'db_table': 'Consumos',
            },
        ),
    ]
