# Generated by Django 4.2.6 on 2024-03-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_consumos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consumos',
            table='tbConsumos',
        ),
        migrations.AlterModelTable(
            name='habitacion',
            table='tbHabitacion',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='tbProducto',
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='tbReserva',
        ),
        migrations.AlterModelTable(
            name='servicio',
            table='tbServicio',
        ),
        migrations.AlterModelTable(
            name='tipohabitacion',
            table='tbTipoHabitacion',
        ),
        migrations.AlterModelTable(
            name='tipoproducto',
            table='tbTipoProducto',
        ),
        migrations.AlterModelTable(
            name='tiposervicio',
            table='tbTipoServicio',
        ),
        migrations.AlterModelTable(
            name='tipousuario',
            table='tbTipoUsuario',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='tbUsuarios',
        ),
    ]
