# Generated by Django 4.2.6 on 2024-03-13 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_consumos_table_alter_habitacion_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura_Respaldo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField(null=True)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ID_Consumo', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tbFactura_Respaldo',
            },
        ),
        migrations.CreateModel(
            name='Reserva_Respaldo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Documento', models.IntegerField(null=True)),
                ('Estado', models.CharField(max_length=20, null=True)),
                ('CantidadAdultos', models.IntegerField(null=True)),
                ('CantidadNiños', models.IntegerField(null=True)),
                ('FechaIngreso', models.DateField(null=True)),
                ('FechaSalida', models.DateField(null=True)),
                ('Nro_habitacion', models.IntegerField(null=True)),
                ('Comentarios', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'tbReserva_Respaldo',
            },
        ),
        migrations.CreateModel(
            name='Usuarios_Respaldo',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Documento', models.IntegerField(unique=True)),
                ('Nombre', models.CharField(max_length=50, null=True)),
                ('Apellido', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('Telefono', models.CharField(max_length=15, null=True)),
                ('Genero', models.CharField(max_length=20, null=True)),
                ('Estado', models.CharField(max_length=20, null=True)),
                ('Contraseña', models.CharField(max_length=255, null=True)),
                ('Id_tipo', models.IntegerField(null=True)),
                ('Fecha_Respaldo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbUsuarios_Respaldo',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField(null=True)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ID_Consumo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.consumos')),
            ],
            options={
                'db_table': 'tbFactura',
            },
        ),
    ]
