# Generated by Django 4.2.6 on 2024-03-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_factura_respaldo_reserva_respaldo_usuarios_respaldo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='usuApellidos',
            new_name='Apellidos',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='usuContraseña',
            new_name='Contraseña',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='usuNombres',
            new_name='Nombres',
        ),
    ]
