# Generated by Django 4.2.6 on 2024-03-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_rename_apellidos_usuarios_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_tipo',
            new_name='tipo',
        ),
    ]
