# Generated by Django 4.2.6 on 2024-03-14 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_rename_id_tipo_usuarios_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumos',
            old_name='Cantidad',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='consumos',
            old_name='Facturado',
            new_name='facturado',
        ),
        migrations.RenameField(
            model_name='consumos',
            old_name='Id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='consumos',
            old_name='ID_Producto',
            new_name='id_Producto',
        ),
        migrations.RenameField(
            model_name='consumos',
            old_name='ID_Reserva',
            new_name='id_Reserva',
        ),
        migrations.RenameField(
            model_name='consumos',
            old_name='ID_Servicio',
            new_name='id_Servicio',
        ),
        migrations.RenameField(
            model_name='consumos',
            old_name='Total',
            new_name='total',
        ),
    ]
