# Generated by Django 4.2.6 on 2024-03-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_rename_cantidad_consumos_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumos',
            old_name='cantidad',
            new_name='cantidad_p',
        ),
        migrations.AddField(
            model_name='consumos',
            name='cantidad_s',
            field=models.IntegerField(null=True),
        ),
    ]
