# Generated by Django 4.2.6 on 2024-03-17 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_rename_cantidad_consumos_cantidad_p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='ID_Consumo',
        ),
        migrations.AddField(
            model_name='factura',
            name='id_Reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.reserva'),
        ),
    ]
