# Generated by Django 5.0.2 on 2024-03-19 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_remove_factura_id_consumo_factura_id_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='estado',
            field=models.CharField(blank=True, default='Activo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo',
            field=models.ForeignKey(blank=True, default='105', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.tipousuario'),
        ),
    ]
