# Generated by Django 4.2.6 on 2024-03-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_alter_usuarios_estado_alter_usuarios_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='usuario_imagenes/'),
        ),
    ]
