# Generated by Django 4.2.6 on 2024-04-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_alter_usuarios_contraseña_alter_usuarios_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='Contraseña',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='comentarios',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
