# Generated by Django 4.0.6 on 2024-04-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_remove_usuarios_contraseña_alter_reserva_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_respaldo',
            name='Comentarios',
            field=models.CharField(default='Sin comentarios por el cliente', max_length=300, null=True),
        ),
    ]
