/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package base_de_datos;

import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author SENA
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(this);
    }
    
    void mostrardatos(String valor){
    
        DefaultTableModel modelo =new DefaultTableModel();
    
        modelo.addColumn("CEDULA");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO");
        modelo.addColumn("EMAIL");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("GENERO");
        
        tabla_clientes.setModel(modelo);
    
        String sql="";
        if (valor.equals("")){
        JOptionPane.showConfirmDialog(null, "usted no digito nada, se va a imprimir todo");
        sql = "SELECT * FROM tbusuarios";
        }else{
        sql = "SELECT * FROM tbusuarios WHERE usuDocumento='"+valor+"'";
        }
    
        String []datos = new String[4];
            try{
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery( sql);

            while (rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);

                modelo.addRow(datos);

                }
                tabla_clientes.setModel(modelo);
                
                
            }catch (SQLException ex){
            
            }

        }



    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        caja_apellido = new javax.swing.JTextField();
        btn_listar = new javax.swing.JButton();
        direccion = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        caja_buscar = new javax.swing.JTextField();
        nombre = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        caja_telefono = new javax.swing.JTextField();
        caja_cedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        caja_eliminar = new javax.swing.JTextField();
        caja_email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        caja_genero = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_clientes = new javax.swing.JTable();
        caja_nombre = new javax.swing.JTextField();
        btn_eliminar = new javax.swing.JButton();
        cedula = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);
        jPanel1.add(caja_apellido);
        caja_apellido.setBounds(79, 108, 137, 22);

        btn_listar.setBackground(new java.awt.Color(204, 255, 153));
        btn_listar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_listar.setText("Listar");
        btn_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_listar);
        btn_listar.setBounds(220, 150, 72, 27);

        direccion.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        direccion.setText("Email");
        jPanel1.add(direccion);
        direccion.setBounds(251, 52, 35, 20);

        telefono.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        telefono.setText("Telefono");
        jPanel1.add(telefono);
        telefono.setBounds(238, 80, 53, 20);

        caja_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(caja_buscar);
        caja_buscar.setBounds(95, 202, 88, 22);

        nombre.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        nombre.setText("Nombre");
        jPanel1.add(nombre);
        nombre.setBounds(15, 80, 51, 20);

        btn_buscar.setBackground(new java.awt.Color(255, 255, 204));
        btn_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar);
        btn_buscar.setBounds(15, 199, 74, 27);
        jPanel1.add(caja_telefono);
        caja_telefono.setBounds(297, 80, 110, 22);
        jPanel1.add(caja_cedula);
        caja_cedula.setBounds(78, 52, 138, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setText("Apellido");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(21, 108, 52, 20);

        caja_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(caja_eliminar);
        caja_eliminar.setBounds(319, 202, 88, 22);
        jPanel1.add(caja_email);
        caja_email.setBounds(297, 52, 110, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Genero");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 110, 45, 20);
        jPanel1.add(caja_genero);
        caja_genero.setBounds(300, 110, 110, 22);

        btn_guardar.setBackground(new java.awt.Color(255, 255, 204));
        btn_guardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardar);
        btn_guardar.setBounds(15, 154, 85, 27);

        tabla_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla_clientes);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 240, 416, 128);
        jPanel1.add(caja_nombre);
        caja_nombre.setBounds(78, 80, 138, 22);

        btn_eliminar.setBackground(new java.awt.Color(204, 255, 153));
        btn_eliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminar);
        btn_eliminar.setBounds(229, 199, 84, 27);

        cedula.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        cedula.setText("Cedula");
        jPanel1.add(cedula);
        cedula.setBounds(28, 52, 44, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuarios");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(178, 8, 99, 32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caja_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_buscarActionPerformed

    private void caja_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_eliminarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_caja_eliminarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:

        try{
            PreparedStatement pst =cn.prepareStatement("INSERT INTO tbusuarios() VALUES(?,?,?,?,?,?)");
            pst.setString(1, caja_cedula.getText());
            pst.setString(2, caja_nombre.getText());
            pst.setString(3, caja_apellido.getText());
            pst.setString(4, caja_email.getText());
            pst.setString(5, caja_telefono.getText());
            pst.setString(6, caja_genero.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "DATOS ALMACENADOS");

        }catch(Exception e){

        }

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarActionPerformed
        // TODO add your handling code here:
        mostrardatos("");
    }//GEN-LAST:event_btn_listarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        try{
            PreparedStatement pst =cn.prepareStatement("DELETE FROM tbusuarios WHERE usuDocumento=?");
            pst.setString(1, caja_eliminar.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "DATOS ELIMINADOS");

        }catch(Exception e){

        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        mostrardatos(caja_buscar.getText());
    }//GEN-LAST:event_btn_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_listar;
    private javax.swing.JTextField caja_apellido;
    private javax.swing.JTextField caja_buscar;
    private javax.swing.JTextField caja_cedula;
    private javax.swing.JTextField caja_eliminar;
    private javax.swing.JTextField caja_email;
    private javax.swing.JTextField caja_genero;
    private javax.swing.JTextField caja_nombre;
    private javax.swing.JTextField caja_telefono;
    private javax.swing.JLabel cedula;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nombre;
    private javax.swing.JTable tabla_clientes;
    private javax.swing.JLabel telefono;
    // End of variables declaration//GEN-END:variables

Conectar cc=new Conectar();
        Connection cn =cc.conexion();

}
